apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections  4096;  ## Default: 1024
    }
    http{
      server {
        listen 80;

        location /posts {
          proxy_pass http://backend-service:3000/posts;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Add other configuration as needed
      }
    }